# Pull tomcat latest image from dockerhub 
From tomcat:11.0.15-jdk25-temurin-noble

# Maintainer
MAINTAINER "AR Shankar" 

# copy war file on to container 
COPY ./webapp.war /usr/local/tomcat/webapps